// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrkYuLFdER2RPgZvbRHlw8BFZkLEdbpfw',
    appId: '1:559621338137:web:2d959fb3de8c38adb26688',
    messagingSenderId: '559621338137',
    projectId: 'braided-hangout-419516',
    authDomain: 'braided-hangout-419516.firebaseapp.com',
    storageBucket: 'braided-hangout-419516.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLMB620vKmsvg3KVGK1kAiCIRG2KVZ7X0',
    appId: '1:559621338137:android:8e24b6643ac625f5b26688',
    messagingSenderId: '559621338137',
    projectId: 'braided-hangout-419516',
    storageBucket: 'braided-hangout-419516.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHYVXM5fQ61jCfjthpmLMSV8-CjMxR3HI',
    appId: '1:559621338137:ios:fff35f155dd8d258b26688',
    messagingSenderId: '559621338137',
    projectId: 'braided-hangout-419516',
    storageBucket: 'braided-hangout-419516.appspot.com',
    iosBundleId: 'com.example.queueEase',
  );
}
